name: Datadog Apps Deploy
description: Build and deploy Vite apps to Datadog
author: Datadog

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: upload-cloud
  color: purple

# Define your inputs here.
inputs:
  datadog-api-key:
    description: Datadog API key
    required: true
  datadog-app-key:
    description: Datadog App key
    required: true
  app-name:
    description: The app identifier in Datadog (used in the API endpoint URL)
    required: true
  app-display-name:
    description: The display name for the app
    required: true
  app-directory:
    description: Root directory of the app
    required: false
    default: '.'
  build-dir:
    description:
      Directory containing the build output, relative to app-directory
    required: false
    default: dist
  build-command:
    description: Command to build the Vite app
    required: false
    default: npm run build
  datadog-site:
    description: Datadog site
    required: false
    default: app.datadoghq.com

runs:
  using: node24
  main: dist/index.js
